import Head from 'next/head';
import React from 'react';

export default function Header() {
  return (
    <header>
      <Head>
        <title>wa2me.com</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        ></meta>
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
    </header>
  );
}
s;
